# src/athena/simulation/validation.py
from typing import Any

from athena.schemas.case import CaseFile
from athena.schemas.state import ValidationResult


def _extract_cited_ids(data: Any, collected: set | None = None) -> set[str]:
    """Recursively extract all ID-like references from agent output."""
    if collected is None:
        collected = set()
    if isinstance(data, dict):
        for key, value in data.items():
            if key in (
                "facts_referenced", "evidence_cited", "norm_text_cited",
                "supports_facts", "legal_basis",
            ):
                if isinstance(value, list):
                    collected.update(v for v in value if isinstance(v, str))
            elif key == "supports" and isinstance(value, str):
                collected.add(value)
            elif key in ("to_argument", "derived_from", "objection_id") and isinstance(value, str):
                collected.add(value)
            elif key == "id" and isinstance(value, str):
                # Agent-generated IDs (ARG1, RARG1) — don't validate these
                pass
            elif key == "precedents_addressed" or key == "precedents_cited":
                if isinstance(value, list):
                    for item in value:
                        if isinstance(item, dict) and "id" in item:
                            collected.add(item["id"])
            else:
                _extract_cited_ids(value, collected)
    elif isinstance(data, list):
        for item in data:
            _extract_cited_ids(item, collected)
    return collected


def validate_agent_output(
    output: dict,
    agent_role: str,
    case: CaseFile,
    appellant_brief: dict | None = None,
    respondent_brief: dict | None = None,
) -> ValidationResult:
    errors: list[str] = []
    warnings: list[str] = []

    # --- Level 1: structure ---
    if agent_role in ("appellant", "respondent"):
        if "filed_brief" not in output:
            errors.append("Output deve contenere 'filed_brief'")
            return ValidationResult(valid=False, errors=errors, warnings=[])
        if "internal_analysis" not in output:
            errors.append("Output deve contenere 'internal_analysis'")
            return ValidationResult(valid=False, errors=errors, warnings=[])

    # --- Level 2: referential integrity ---
    valid_ids = case.extract_all_ids()
    # Also add IDs generated by appellant (for respondent/judge validation)
    if appellant_brief and "filed_brief" in appellant_brief:
        for arg in appellant_brief["filed_brief"].get("arguments", []):
            valid_ids.add(arg["id"])
    if respondent_brief and "filed_brief" in respondent_brief:
        for defense in respondent_brief["filed_brief"].get("affirmative_defenses", []):
            valid_ids.add(defense["id"])

    cited_ids = _extract_cited_ids(output)
    # Filter out None values
    cited_ids.discard(None)
    phantom_ids = cited_ids - valid_ids
    if phantom_ids:
        errors.append(f"ID inesistenti nel fascicolo: {phantom_ids}")

    # --- Level 3: completeness ---
    if agent_role == "respondent" and appellant_brief:
        appellant_arg_ids = {
            a["id"] for a in appellant_brief["filed_brief"]["arguments"]
        }
        responded_to = {
            r["to_argument"]
            for r in output["filed_brief"].get("responses_to_opponent", [])
        }
        missed = appellant_arg_ids - responded_to
        if missed:
            errors.append(f"Argomenti opponente non affrontati: {missed}")

    if agent_role == "judge" and appellant_brief:
        all_arg_ids = set()
        all_arg_ids.update(
            a["id"] for a in appellant_brief["filed_brief"]["arguments"]
        )
        if respondent_brief and "filed_brief" in respondent_brief:
            all_arg_ids.update(
                d["id"]
                for d in respondent_brief["filed_brief"].get("affirmative_defenses", [])
            )
        evaluated = {
            e["argument_id"] for e in output.get("argument_evaluation", [])
        }
        missed = all_arg_ids - evaluated
        if missed:
            errors.append(f"Argomenti non valutati dal giudice: {missed}")

    # --- Warnings ---
    if agent_role in ("appellant", "respondent"):
        assessments = output.get("internal_analysis", {}).get(
            "strength_self_assessments", {}
        )
        if assessments and all(v > 0.8 for v in assessments.values()):
            warnings.append(
                "Tutti i self_assessment > 0.8 — possibile mancanza di autocritica"
            )
        if not output.get("internal_analysis", {}).get("gaps"):
            warnings.append(
                "Campo 'gaps' vuoto — verificare completezza fascicolo"
            )

    return ValidationResult(
        valid=len(errors) == 0, errors=errors, warnings=warnings
    )
