# src/athena/simulation/validation.py
from typing import Any

from athena.schemas.case import CaseFile
from athena.schemas.state import ValidationResult


def _extract_cited_ids(data: Any, collected: set | None = None) -> set[str]:
    """Recursively extract all ID-like references from agent output."""
    if collected is None:
        collected = set()
    if isinstance(data, dict):
        for key, value in data.items():
            if key in (
                "facts_referenced", "evidence_cited", "norm_text_cited",
                "supports_facts", "legal_basis",
            ):
                if isinstance(value, list):
                    collected.update(v for v in value if isinstance(v, str))
            elif key == "supports" and isinstance(value, str):
                # Intra-brief reference (ARG2 supports ARG1) — skip, not a case file ID
                pass
            elif key in ("to_argument", "derived_from", "objection_id") and isinstance(value, str):
                collected.add(value)
            elif key == "id" and isinstance(value, str):
                # Agent-generated IDs (ARG1, RARG1) — don't validate these
                pass
            elif key == "precedents_addressed" or key == "precedents_cited":
                if isinstance(value, list):
                    for item in value:
                        if isinstance(item, dict) and "id" in item:
                            collected.add(item["id"])
            else:
                _extract_cited_ids(value, collected)
    elif isinstance(data, list):
        for item in data:
            _extract_cited_ids(item, collected)
    return collected


def validate_agent_output(
    output: dict,
    agent_role: str,
    case: CaseFile,
    appellant_brief: dict | None = None,
    respondent_brief: dict | None = None,
    prior_briefs: dict[str, dict] | None = None,
) -> ValidationResult:
    """Validate agent output for structure, referential integrity, and completeness.

    Args:
        output: Agent output dict.
        agent_role: "appellant", "respondent", "judge", "advocate", or "adjudicator".
        case: CaseFile for ID extraction.
        appellant_brief: Legacy — single appellant brief.
        respondent_brief: Legacy — single respondent brief.
        prior_briefs: N-party — dict of party_id → brief from prior phases.
    """
    errors: list[str] = []
    warnings: list[str] = []

    # Normalize role for checks
    is_advocate = agent_role in ("appellant", "respondent", "advocate")
    is_adjudicator = agent_role in ("judge", "adjudicator")

    # --- Level 1: structure ---
    if is_advocate:
        if "filed_brief" not in output:
            errors.append("Output deve contenere 'filed_brief'")
            return ValidationResult(valid=False, errors=errors, warnings=[])
        if "internal_analysis" not in output:
            errors.append("Output deve contenere 'internal_analysis'")
            return ValidationResult(valid=False, errors=errors, warnings=[])

    # --- Build valid IDs ---
    valid_ids = case.extract_all_ids()

    # Collect all prior brief IDs (N-party or legacy)
    all_prior_briefs = dict(prior_briefs) if prior_briefs else {}
    if appellant_brief and not prior_briefs:
        all_prior_briefs["_appellant"] = appellant_brief
    if respondent_brief and not prior_briefs:
        all_prior_briefs["_respondent"] = respondent_brief

    # Add IDs generated by prior parties
    all_prior_arg_ids: set[str] = set()
    for pid, brief in all_prior_briefs.items():
        if brief and "filed_brief" in brief:
            fb = brief["filed_brief"]
            for arg in fb.get("arguments", []):
                valid_ids.add(arg["id"])
                all_prior_arg_ids.add(arg["id"])
            for defense in fb.get("affirmative_defenses", []):
                valid_ids.add(defense["id"])
                all_prior_arg_ids.add(defense["id"])

    # --- Level 2: referential integrity ---
    cited_ids = _extract_cited_ids(output)
    cited_ids.discard(None)
    phantom_ids = cited_ids - valid_ids
    if phantom_ids:
        errors.append(f"ID inesistenti nel fascicolo: {phantom_ids}")

    # --- Level 3: completeness ---
    # Responding party must address all arguments from prior-phase parties
    if agent_role == "respondent" or (is_advocate and all_prior_briefs):
        # Collect all argument IDs from prior parties that filed arguments
        prior_arg_ids: set[str] = set()
        # Check legacy appellant_brief
        if appellant_brief and "filed_brief" in (appellant_brief or {}):
            prior_arg_ids.update(
                a["id"] for a in appellant_brief["filed_brief"].get("arguments", [])
            )
        # Check N-party prior_briefs (only those with "arguments" = filing parties)
        if prior_briefs:
            for pid, brief in prior_briefs.items():
                if brief and "filed_brief" in brief:
                    prior_arg_ids.update(
                        a["id"] for a in brief["filed_brief"].get("arguments", [])
                    )

        if prior_arg_ids and "filed_brief" in output:
            responded_to = {
                r["to_argument"]
                for r in output["filed_brief"].get("responses_to_opponent", [])
            }
            missed = prior_arg_ids - responded_to
            if missed:
                errors.append(f"Argomenti opponente non affrontati: {missed}")

    if is_adjudicator or agent_role == "judge":
        # Judge must evaluate all arguments from all parties
        all_arg_ids: set[str] = set()
        for pid, brief in all_prior_briefs.items():
            if brief and "filed_brief" in brief:
                fb = brief["filed_brief"]
                all_arg_ids.update(a["id"] for a in fb.get("arguments", []))
                all_arg_ids.update(d["id"] for d in fb.get("affirmative_defenses", []))

        if all_arg_ids:
            evaluated = {
                e["argument_id"] for e in output.get("argument_evaluation", [])
            }
            missed = all_arg_ids - evaluated
            if missed:
                errors.append(f"Argomenti non valutati dal giudice: {missed}")

    # --- Warnings ---
    if is_advocate:
        assessments = output.get("internal_analysis", {}).get(
            "strength_self_assessments", {}
        )
        numeric_assessments = []
        for v in assessments.values():
            try:
                numeric_assessments.append(float(v))
            except (ValueError, TypeError):
                warnings.append(
                    f"self_assessment non numerico: {str(v)[:80]} — attesi valori 0.0-1.0"
                )
        if numeric_assessments and all(v > 0.8 for v in numeric_assessments):
            warnings.append(
                "Tutti i self_assessment > 0.8 — possibile mancanza di autocritica"
            )
        if not output.get("internal_analysis", {}).get("gaps"):
            warnings.append(
                "Campo 'gaps' vuoto — verificare completezza fascicolo"
            )

    return ValidationResult(
        valid=len(errors) == 0, errors=errors, warnings=warnings
    )
